import jsPDF from "jspdf";
import { format } from "date-fns";
import { Message } from "@/types/messages";
import { ApiMessageHistory } from "@/lib/api";
import { getSenderName } from "@/lib/messages";

export type Conversation = {
  user_id: string;
  name: string;
  role: string;
  caseRef: string;
  childName?: string | null;
};

const formatDateTime = (value: string) =>
  format(new Date(value), "yyyy-MM-dd HH:mm");

const formatHistoryLabel = (entry: ApiMessageHistory) => {
  const when = formatDateTime(entry.action_at);

  switch (entry.action_type) {
    case "create":
      return `Original (${when})`;
    case "update":
      return `Edited (${when})`;
    case "delete":
      return `Deleted (${when})`;
    default:
      return `Event (${when})`;
  }
};

export const exportConversation = async (
  messages: Message[],
  conversation: Conversation,
  purposeFilter: string,
  historyByMessageId: Record<string, ApiMessageHistory[]> = {}
) => {
  const exportedMessages =
    purposeFilter === "All"
      ? messages
      : messages.filter((m) => m.purpose === purposeFilter);

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // Layout (South African legal-document-friendly defaults)
  const margin = 25.4; // 1 inch
  const indent = 12.7; // 0.5 inch
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxWidth = pageWidth - margin * 2;

  // Typography
  const bodyFontPt = 12;
  const footFontPt = 10;
  const bodyLineMm = bodyFontPt * 0.3528 * 1.5; // ~1.5 spacing
  const footLineMm = footFontPt * 0.3528; // ~single spacing

  let y = margin;

  const addPageIfNeeded = (neededMm: number) => {
    if (y + neededMm <= pageHeight - margin) return;
    doc.addPage();
    y = margin;
  };

  const writeWrapped = (text: string, x: number, fontPt: number, lineMm: number) => {
    doc.setFont("times", "normal");
    doc.setFontSize(fontPt);
    const lines = doc.splitTextToSize(text, maxWidth - (x - margin));
    addPageIfNeeded(lines.length * lineMm);
    doc.text(lines, x, y);
    y += lines.length * lineMm;
  };

  const writeHeading = (text: string, level: 1 | 2) => {
    doc.setFont("times", "bold");
    doc.setFontSize(level === 1 ? 14 : 12);
    const lines = doc.splitTextToSize(text, maxWidth);
    addPageIfNeeded(lines.length * bodyLineMm);
    doc.text(lines, margin, y);
    y += lines.length * bodyLineMm;
  };

  const writeClause = (numbering: string, text: string) => {
    doc.setFont("times", "normal");
    doc.setFontSize(bodyFontPt);

    const prefix = `${numbering} `;
    const prefixWidth = doc.getTextWidth(prefix);

    const available = maxWidth - prefixWidth;
    const lines = doc.splitTextToSize(text, available);
    addPageIfNeeded(lines.length * bodyLineMm);

    doc.text(prefix, margin, y);
    doc.text(lines, margin + prefixWidth, y);
    y += lines.length * bodyLineMm;
  };

  const writeIndentedParagraph = (text: string) => {
    doc.setFont("times", "normal");
    doc.setFontSize(bodyFontPt);
    const lines = doc.splitTextToSize(text, maxWidth - indent);
    addPageIfNeeded(lines.length * bodyLineMm);
    doc.text(lines, margin + indent, y);
    y += lines.length * bodyLineMm;
  };

  const writeFootnote = (text: string) => {
    doc.setFont("times", "normal");
    doc.setFontSize(footFontPt);
    const lines = doc.splitTextToSize(text, maxWidth);
    addPageIfNeeded(lines.length * footLineMm);
    doc.text(lines, margin, y);
    y += lines.length * footLineMm;
  };

  // Title block
  doc.setFont("times", "bold");
  doc.setFontSize(16);
  addPageIfNeeded(bodyLineMm * 2);
  doc.text("CONVERSATION RECORD (PDF EXPORT)", pageWidth / 2, y, { align: "center" });
  y += bodyLineMm;

  doc.setFont("times", "normal");
  doc.setFontSize(bodyFontPt);
  doc.text(`Case reference: ${conversation.caseRef || "-"}`, pageWidth / 2, y, { align: "center" });
  y += bodyLineMm;

  y += bodyLineMm * 0.5;
  writeFootnote(`Exported: ${new Date().toLocaleString()}`);
  writeFootnote(`Filter applied: ${purposeFilter}`);
  y += bodyLineMm * 0.5;

  // Parties
  writeHeading("1. Parties", 1);
  writeClause("1.1", `Participant A (exporting user): You.`);
  writeClause("1.2", `Participant B: ${conversation.name}.`);
  writeClause("1.3", `Role (Participant B): ${conversation.role}.`);
  if (conversation.childName) {
    writeClause("1.4", `Child: ${conversation.childName}.`);
  }
  y += bodyLineMm * 0.5;

  // Reliability / audit trail clauses (plain language)
  writeHeading("2. Reliability and audit trail", 1);
  writeClause(
    "2.1",
    "This record is generated by the CUB application as a PDF export of an in-app conversation."
  );
  writeClause(
    "2.2",
    "Message timestamps reflect the system time recorded by the application services at the time of sending or updating."
  );
  writeClause(
    "2.3",
    "This PDF is not password-protected and is intended to be readable and shareable for review, mediation, or court-related purposes."
  );
  writeClause(
    "2.4",
    "Edits and deletions (where applicable) are reflected in the history entries included beneath each message."
  );
  writeClause(
    "2.5",
    "Where a message is edited after being seen, the edited version may be marked as unseen until it is viewed again by the recipient."
  );
  y += bodyLineMm * 0.75;

  // Transcript
  writeHeading("3. Conversation transcript", 1);
  writeClause(
    "3.1",
    "The transcript below is listed in chronological order (oldest to newest), showing messages as sent."
  );
  y += bodyLineMm * 0.25;

  let messageNo = 0;
  exportedMessages.forEach((msg) => {
    messageNo += 1;

    const senderName = getSenderName(msg.sender, conversation);
    const recipientName = msg.sender === "me" ? conversation.name : "You";
    const historyEntries = historyByMessageId[msg.id] ?? [];
    const sortedHistory = historyEntries
      .slice()
      .sort((a, b) => new Date(a.action_at).getTime() - new Date(b.action_at).getTime());
    const isDeleted = sortedHistory.some((entry) => entry.action_type === "delete");

    const status =
      msg.status === "Read" ? "Seen" : msg.status ? "Unseen" : "Unspecified";
    const edited =
      Boolean(msg.updated_at) && msg.updated_at !== msg.createdAt ? "Edited" : null;

    // Message header line
    doc.setFont("times", "bold");
    doc.setFontSize(bodyFontPt);
    const header = `3.${messageNo}  ${formatDateTime(msg.createdAt)}  ${senderName} → ${recipientName}  (${msg.purpose})`;
    const headerLines = doc.splitTextToSize(header, maxWidth);
    addPageIfNeeded(headerLines.length * bodyLineMm);
    doc.text(headerLines, margin, y);
    y += headerLines.length * bodyLineMm;

    doc.setFont("times", "normal");
    const metaParts = [
      `Status: ${status}`,
      edited ? `State: ${edited}` : null,
      isDeleted ? "Deleted: Yes" : "Deleted: No",
    ].filter(Boolean);
    writeIndentedParagraph(metaParts.join(" · "));

    // Content paragraph (indented)
    const contentLabel = isDeleted ? "Current content (deleted):" : "Current content:";
    writeIndentedParagraph(`${contentLabel} ${msg.content}`);

    // Attachments (indented)
    msg.attachments?.forEach((att) => {
      writeIndentedParagraph(`Attachment: ${att.name} (${att.type}).`);
    });

    // History (indented, single-spaced-ish via foot font)
    if (sortedHistory.length > 0) {
      y += bodyLineMm * 0.25;
      doc.setFont("times", "bold");
      doc.setFontSize(bodyFontPt);
      addPageIfNeeded(bodyLineMm);
      doc.text("History:", margin + indent, y);
      y += bodyLineMm;

      sortedHistory.forEach((entry) => {
        writeFootnote(`- ${formatHistoryLabel(entry)}`);
        if (entry.content) {
          writeFootnote(`  Content: ${entry.content}`);
        }
      });
    }

    y += bodyLineMm * 0.5;
  });

  doc.save(`conversation-${conversation.user_id}.pdf`);
};















