import { http } from "@/lib/http";

export const uploadVaultDocument = async ({
  file,
  childId,
  vaultId,
}: {
  file: File;
  childId: string;
  vaultId: string;
}): Promise<string> => {
  // Private end-to-end: backend issues a short-lived signed upload URL using Supabase service role.
  // This avoids any public/anon INSERT policies on the bucket.
  void childId; // kept for compatibility with existing call sites

  const ticket = await http<{ path: string; signed_url: string }>(
    `/vaults/${vaultId}/documents/signed-upload`,
    "POST",
    {
      filename: file.name || "document",
      content_type: file.type || "application/octet-stream",
    },
  );

  const uploadRes = await fetch(ticket.signed_url, {
    method: "PUT",
    headers: {
      "Content-Type": file.type || "application/octet-stream",
    },
    body: file,
  });

  if (!uploadRes.ok) {
    const text = await uploadRes.text().catch(() => "");
    throw new Error(`Upload failed (${uploadRes.status}): ${text || "Unable to upload file"}`);
  }

  return ticket.path;
};

export const getSignedVaultDocumentUrl = async (
  fileUrlOrPath: string,
  expiresInSeconds = 60 * 10,
): Promise<string> => {
  throw new Error(
    "Signed URLs are now generated by the backend. Use `/api/vaults/documents/:id/signed-url` instead.",
  );
};
